@base_url = http://localhost:5000/api/skill

### GET PROJECTS
GET {{base_url}}/all

### ADD PROJECT
POST {{base_url}}/add
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="name"

Blender
--boundary123
Content-Disposition: form-data; name="colorInvert"

false
--boundary123
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< image_path
--boundary123--

### EDİT PROJECT
PUT {{base_url}}/edit/676a811e7015a2ba52549f6e
Content-Type: multipart/form-data; boundary=boundary456

--boundary456
Content-Disposition: form-data; name="colorInvert"

true
--boundary456
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< image_path
--boundary456--

### DELETE PROJECT
DELETE {{base_url}}/delete/676a811e7015a2ba52549f6e

### DELETE ALL PROJECTS
DELETE {{base_url}}/delete/all